### ISSUE TITLE
BLDC over Serial/CanBus version?

### ISSUE THREAD

**Issue by samuk** [eeduro/eeduro-delta#1]
I'm kicking around an idea to make a Delta using BLDC motors, using serial or CanBUS comms.

Provisional BOM: https://github.com/Agroecology-Lab/Open-Weeding-Delta/blob/master/hardware/readme.md#kinematics-software

Would your HAL be flexible to accommodate that so I could use your code without major rewrites?

The motor drivers would provide a [serial commander interface](https://docs.simplefoc.com/commander_interface)

**Comment by ursgraf** [comment]
That should be no problem. Our HAL simply deals with how to physically access the underlying hardware. We support various types of HAL's, such as EtherCAT, external ADC/DAC, CANopen.

**Comment by samuk** [comment]
Great, I'll investigate further and report back any actual issues.

Great to spot you have a ROS2 wrapper: https://github.com/eeros-project/ros-eeros

Did you have any comments on my proposed hardware? https://github.com/Agroecology-Lab/Open-Weeding-Delta/blob/master/hardware/readme.md#reference-hardware
